apiVersion: apps/v1
kind: Deployment
metadata:
  name: igrisca-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igrisca
  template:
    metadata:
      labels:
        app: igrisca
    spec:
      containers:
        - image: ts4894/igrisca:2021-11-30-19-20-02
          name: igrisca
          # tu moraš dati pravo bazo (postres baza je se mi zdi; ne bo cez elephantSQL)
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://lallah.db.elephantsql.com:5432/kryfltbl
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: kryfltbl
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: igrisca
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: igrisca
