kumuluzee:
  name: igrisca-service
  env:
    name: dev
  version: 1.0.0
  cors-filter:
    annotations:
      my-resource:
        allow-origin: "http://kumuluz.com"
        allow-subdomains: false
  server:
    base-url: http://20.85.139.182:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/IgriscaMetadataDS
      connection-url: jdbc:postgresql://igrisca-db.postgres.database.azure.com:5432/postgres?user=postgresAdmin&password=IgriscaDBPass123&sslmode=require
      username: postgresAdmin
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/IgriscaMetadataDS
      disk-space-health-check:
        threshold: 100000000
      http-health-check:
        - connection-url: https://github.com/RSO-football
    metrics:
      web-instrumentation:
        - name: igrisca-endpoint
          url-pattern: /v1/igrisca/*
rest-properties:
  maintenance-mode: false
  broken: false