kumuluzee:
  name: igrisca-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/IgriscaMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/igrisca
      username: postgres
      password: postgres
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/IgriscaMetadataDS
    metrics:
      web-instrumentation:
        - name: igrisca-endpoint
          url-pattern: /v1/igrisca/*
rest-properties:
  maintenance-mode: false
  broken: false