kumuluzee:
  name: igrisca-service
  env:
    name: dev
  version: 1.0.0
  cors-filter:
    annotations:
      my-resource:
        allow-origin: "http://kumuluz.com"
        allow-subdomains: false
  server:
    base-url: http://20.85.139.182:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/IgriscaMetadataDS
      connection-url: jdbc:postgresql://igrisca-db.postgres.database.azure.com:5432/postgres?user=postgresAdmin&password=IgriscaDBPass123&sslmode=require
      username: postgresAdmin
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/IgriscaMetadataDS
      disk-space-health-check:
        threshold: 100000000
      http-health-check:
        - connection-url: https://github.com/RSO-football
    metrics:
      web-instrumentation:
        - name: igrisca-endpoint
          url-pattern: /v1/igrisca/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="b018540f-f4da-408b-afe6-d9e1251ff783-ls.logit.io"
                                  port="24836" protocol="udp">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="trace" />
                                  </Root>
                              </Loggers>
                          </Configuration>'
rest-properties:
  maintenance-mode: false
  broken: false