kumuluzee:
  name: igrisca-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/IgriscaMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/igrisca
      username: postgres
      password: postgres
rest-properties:
  maintenance-mode: false